# Introduction to Numpy
Learning NumPy!

In [2]:
import numpy as np
np.__version__

'1.23.1'

## Differences between lists and NumPy Arrays
* List are mutable
* List can have only same data type

In [4]:
gpas_as_list = [4.0, 3.286, 3.5]

In [5]:
#Can append elements
gpas_as_list.append(4.0)
#Can have multiple datatypes in it
gpas_as_list.insert(1, "whatever")
#Can remove items
gpas_as_list.pop(1)

'whatever'

In [6]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0]

In [7]:
gpas = np.array(gpas_as_list)

In [8]:
?gpas

In [9]:
gpas.dtype

dtype('float64')

In [10]:
gpas.itemsize

8

In [12]:
gpas.size

4

In [13]:
len(gpas)

4

In [12]:
gpas.nbytes

32

## Multideminsional Arrays aka ndarrays
* example is a 2d array aka matrix 
* nested arrays in other arrays to create a higer degree

In [14]:
students_gpas = np.array([[4.0, 3.286, 3.5, 4.0],
                         [3.2, 2.8, 4.0, 4.0],
                         [3.96, 3.92, 4.0, 4.0]
                         ],np.float16)
students_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 2.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [15]:
students_gpas.ndim

2

In [16]:
students_gpas.shape

(3, 4)

In [17]:
students_gpas.size

12

In [18]:
len(students_gpas)

3

In [19]:
students_gpas.itemsize

2

In [20]:
%whos ndarray

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [21]:
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2ad0e8c7de0
byteorder:  little
byteswap:  False
type: float16


In [22]:
students_gpas[2]

array([3.96, 3.92, 4.  , 4.  ], dtype=float16)

In [24]:
students_gpas[2][3]

4.0

## About data types
* Possible to change data types based on size and if signed to save space

In [3]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [6]:
%whos

Variable        Type       Data/Info
------------------------------------
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [7]:
study_minutes[0] = 150

In [8]:
first_day_minutes  = study_minutes[0]

In [9]:
first_day_minutes

150

In [10]:
type(first_day_minutes)

numpy.uint16

In [11]:
study_minutes[1] = 60

In [12]:
study_minutes

array([150,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [14]:
study_minutes[2:6] = [80,60,30,90]
study_minutes

array([150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)