# Introduction to Numpy
Learning NumPy!

In [1]:
import numpy as np
np.__version__

'1.23.1'

## Differences between lists and NumPy Arrays
* List are mutable
* List can have only same data type

In [2]:
gpas_as_list = [4.0, 3.286, 3.5]

In [3]:
#Can append elements
gpas_as_list.append(4.0)
#Can have multiple datatypes in it
gpas_as_list.insert(1, "whatever")
#Can remove items
gpas_as_list.pop(1)

'whatever'

In [4]:
gpas_as_list

[4.0, 3.286, 3.5, 4.0]

In [5]:
gpas = np.array(gpas_as_list)

In [6]:
?gpas

In [7]:
gpas.dtype

dtype('float64')

In [8]:
gpas.itemsize

8

In [9]:
gpas.size

4

In [10]:
len(gpas)

4

In [11]:
gpas.nbytes

32

## Multideminsional Arrays aka ndarrays
* example is a 2d array aka matrix 
* nested arrays in other arrays to create a higer degree
* Rank defines how many dimensions an array contains
* Shape defines the length of each of the array's dimensions
* Each dimension is also refereed to as an axis, and they are zero-indexed Multiples are called axes.

In [14]:
students_gpas = np.array([[4.0, 3.286, 3.5, 4.0],
                         [3.2, 2.8, 4.0, 4.0],
                         [3.96, 3.92, 4.0, 4.0]
                         ],np.float16)
students_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 2.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [15]:
students_gpas.ndim

2

In [16]:
students_gpas.shape

(3, 4)

In [17]:
students_gpas.size

12

In [18]:
len(students_gpas)

3

In [19]:
students_gpas.itemsize

2

In [20]:
%whos ndarray

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [21]:
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2ad0e8c7de0
byteorder:  little
byteswap:  False
type: float16


In [22]:
students_gpas[2]

array([3.96, 3.92, 4.  , 4.  ], dtype=float16)

In [24]:
students_gpas[2][3]

4.0

## About data types
* Possible to change data types based on size and if signed to save space

In [13]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [14]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [15]:
study_minutes[0] = 150

In [16]:
first_day_minutes  = study_minutes[0]

In [17]:
first_day_minutes

150

In [18]:
type(first_day_minutes)

numpy.uint16

In [19]:
study_minutes[1] = 60

In [20]:
study_minutes

array([150,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

In [21]:
study_minutes[2:6] = [80,60,30,90]


## Creation
* Random state: a seed for rng to start at
* Appending row: have to use np.append since ndarrays are immutable
## Indexing
* Shortcut(tuple): use a tuple instead of seperate brackets 
* Fancy Indexing: making ndarrays subsets from other ndarrays

In [24]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])

In [29]:
study_minutes.shape


(2, 100)

In [28]:
study_minutes[1][0]= 60

In [30]:
study_minutes[1,0]

60

In [31]:
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size = 100, dtype=np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [32]:
[fake_log[3], fake_log[8]]

[44, 50]

In [33]:
fake_log[[3,8]]

array([44, 50], dtype=uint16)

In [34]:
index = np.array([
    [3,8],
    [0,1]
])
fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [36]:
study_minutes = np.append(study_minutes, [fake_log], axis = 0)

In [38]:
study_minutes[1,1] = 360

In [40]:
study_minutes

array([[150,  60,  80,  60,  30,  90,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 60, 360,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   